export {
	type ExtensionDiscoveryCandidate,
	type ExtensionDiscoveryCandidateKind,
	type ExtensionDiscoveryResult,
	type ExtensionIdentity,
	type ExtensionInterceptorRegistration,
	type ExtensionLoadAvailableResult,
	ExtensionLoader,
	type ExtensionObserverRegistration,
	type ExtensionRoot,
	type ExtensionSource,
	type ExtensionToolContribution,
	type LoadExtensionScopeOptions,
	type LoadedExtensionScope,
} from "./loader.ts";
export {
	type ExtensionModuleImporter,
	JitiExtensionModuleImporter,
} from "./module-importer.ts";
export {
	type ExtensionHookSnapshot,
	ExtensionRunner,
	type ExtensionRunnerOptions,
	type ExtensionRunnerSnapshot,
	type ExtensionToolContributionSnapshot,
} from "./runner.ts";
export type {
	ExtensionActionFailure,
	ExtensionActions,
	ExtensionActivationApi,
	ExtensionCommandContext,
	ExtensionCommandContextActions,
	ExtensionContext,
	ExtensionContextActions,
	ExtensionCustomEntry,
	ExtensionFactory,
	ExtensionInterceptorEventFor,
	ExtensionInterceptorFor,
	ExtensionInterceptorName,
	ExtensionInterceptorResultFor,
	ExtensionObservedEvent,
	ExtensionObservedEventName,
	ExtensionObserver,
	ExtensionObserverFor,
	ExtensionSessionActions,
	ExtensionSessionContext,
	ToolDefinition,
	ToolDefinitionPatch,
	ToolExecute,
	ToolExecuteMiddleware,
	ToolExecutionContext,
	ToolExtensionContext,
	ToolLifecycleEvent,
	ToolSource,
} from "./types.ts";
