export {
	type ExtensionCommandContribution,
	type ExtensionDiscoveryCandidate,
	type ExtensionDiscoveryCandidateKind,
	type ExtensionDiscoveryResult,
	type ExtensionIdentity,
	type ExtensionInterceptorRegistration,
	type ExtensionLoadAvailableResult,
	ExtensionLoader,
	type ExtensionObserverRegistration,
	type ExtensionRoot,
	type ExtensionSource,
	type ExtensionToolContribution,
	type LoadExtensionScopeOptions,
	type LoadedExtensionScope,
} from "./loader.ts";
export {
	type ExtensionModuleImporter,
	JitiExtensionModuleImporter,
} from "./module-importer.ts";
export {
	type ExtensionCommandSnapshot,
	type ExtensionHookSnapshot,
	type ExtensionInputInterceptRun,
	ExtensionRunner,
	type ExtensionRunnerOptions,
	type ExtensionRunnerSnapshot,
	type ExtensionToolContributionSnapshot,
	type ResolvedExtensionCommand,
	type ResolvedExtensionInlineCommand,
	type ResolvedExtensionLineCommand,
} from "./runner.ts";
export type {
	ExtensionActionFailure,
	ExtensionActions,
	ExtensionActivationApi,
	ExtensionCommandArguments,
	ExtensionCommandContext,
	ExtensionCommandContextActions,
	ExtensionCommandDefinition,
	ExtensionCommandHandler,
	ExtensionContext,
	ExtensionContextActions,
	ExtensionCoreActions,
	ExtensionCustomEntry,
	ExtensionExecResult,
	ExtensionFactory,
	ExtensionInlineCommandDefinition,
	ExtensionInlineCommandExpand,
	ExtensionInputEvent,
	ExtensionInputResult,
	ExtensionInterceptorEventFor,
	ExtensionInterceptorFor,
	ExtensionInterceptorName,
	ExtensionInterceptorResultFor,
	ExtensionLineCommandDefinition,
	ExtensionObservedEvent,
	ExtensionObservedEventFor,
	ExtensionObservedEventName,
	ExtensionObserver,
	ExtensionObserverFor,
	ExtensionSessionActions,
	ExtensionSessionContext,
	ToolDefinition,
	ToolDefinitionPatch,
	ToolExecute,
	ToolExecuteMiddleware,
	ToolExecutionContext,
	ToolExtensionContext,
	ToolSource,
} from "./types.ts";
